# Generated by Django 5.0.2 on 2024-02-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_airline_runway'),
    ]

    operations = [
        migrations.AddField(
            model_name='runway',
            name='length',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runway',
            name='runway_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runway',
            name='width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
